name: Build Koda
on: [push]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: koda_installer.exe
            path: target/release/koda.exe
          - os: macos-latest
            artifact_name: koda_installer_mac
            path: target/release/koda
          - os: ubuntu-latest
            artifact_name: koda_installer_linux
            path: target/release/koda

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary
        run: cargo build --release

      - name: Prepare Windows Artifact
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path "${{ matrix.path }}") {
            Copy-Item "${{ matrix.path }}" -Destination "${{ matrix.artifact_name }}"
          }
        shell: pwsh

      - name: Prepare Unix Artifact
        if: matrix.os != 'windows-latest'
        run: |
          if [ -f "${{ matrix.path }}" ]; then
            cp "${{ matrix.path }}" "${{ matrix.artifact_name }}"
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: koda-${{ matrix.os }}
          path: koda_installer*
