name: Build Koda
on: [push]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: koda_win.exe
            path: target/release/koda.exe
          - os: macos-latest
            artifact_name: koda_mac
            path: target/release/koda
          - os: ubuntu-latest
            artifact_name: koda_linux
            path: target/release/koda

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary
        run: cargo build --release

      - name: Rename and Move (Windows)
        if: matrix.os == 'windows-latest'
        run: Copy-Item "target/release/koda.exe" -Destination "koda_win.exe"
        shell: pwsh

      - name: Rename and Move (Unix)
        if: matrix.os != 'windows-latest'
        run: cp target/release/koda koda_installer
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: koda-${{ matrix.os }}
          path: koda_*
